import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/shared/Navbar";
import Footer from "@/shared/Footer";

export const metadata: Metadata = {
  title: "ANXSYS",
  description: "Generated by aNXSYS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#f7f8fc]">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
